version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: 
      context: .
    environment:
      DB_TYPE: ${DB_TYPE:-sqlite}
      DB_STORAGE: ${DB_STORAGE:-memory}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-"127.0.0.1,192.168.0.1"} 
      GIN_MODE: ${GIN_MODE:-development}
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-mydb}
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: {}
